### PR TITLE
Added cmake stuff

### PR DESCRIPTION
**Pull request by JonnyPtn**
hopefully makes it easier for everyone else to build :)

### CODE REVIEW

**Comment by larsXYZ** [comment]
Cmake stuff

**Comment by JonnyPtn** [comment]
Not interested?

**Comment by larsXYZ** [comment]
Oh I'm sorry. I've never used github.com before. I'm very interested,  did I do anything wrong? Thanks by the way =)

**Comment by JonnyPtn** [comment]
Haha thought that might be the case :P looks like you closed it instead of merging. I can send another request along with the fix to the typo (finnPlanet instead of findPlanet) too if you want? that should allow anyone to clone and build "out of the box"

**Comment by larsXYZ** [comment]
That would be great!

**Pull request closed without merging**
